version: '3'
services:
  sports_data_crawler:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/sports_data_crawler:0.7
    container_name: crawler
    environment:
      DB_HOST: 192.168.31.73
      DB_PORT: 3306
      DB_USERNAME: allen
      DB_PASSWORD: aldbpw

  simple_sports_data_analyzer:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/simple_sports_data_analyzer:0.6
    container_name: analyzer
    environment:
      DB_HOST: 192.168.31.73
      DB_PORT: 3306
      DB_USERNAME: allen
      DB_PASSWORD: aldbpw

  nosql_converter:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    image: allensyk/nosql_converter:0.5
    container_name: converter
    environment:
      DB_HOST: 192.168.31.73
      DB_PORT: 3306
      DB_USERNAME: allen
      DB_PASSWORD: aldbpw
      MONGO_HOST: 192.168.31.73
      MONGO_PORT: 27017

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    environment:
      PMA_HOST: 192.168.31.73
      PMA_PORT: 3306
    ports:
      - 8080:80

  mongodb:
    image: mongo
    container_name: mongodb
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: allen
      # MONGO_INITDB_ROOT_PASSWORD: password
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: password
      # MONGO_INITDB_DATABASE: kais
    ports:
      - 27017:27017
    volumes:
      - '/home/allen/Temp:/data/db'
    deploy:
      restart_policy:
        condition: always


