cronjob: "3 23 * * *"

image:
  repository: allensyk/kaiji-crawler
  tag: 1.1.0

config:
  log:
    level: DEBUG

  timezone: Asia/Taipei

  commander:
    queryPeriod: 5 # second

  mongo:
    db: kaiji
    host: 192.168.31.73
    port: 27017
    username: 
    password: 