# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: crawler-conf
  namespace: default
data:
  config.yaml: |
    dateFormat: '%Y%m%d'

    logging:
      level: "{{ .Values.config.log.level }}"
    
    crawler:
      dateFormat: '%Y%m%d'
      urlPattern: https://www.playsport.cc/predictgame.php?action=scale&allianceid={game_type}&gametime={game_date}&sid={group_type}
    
    commander:
      queryPeriod: {{ .Values.config.commander.queryPeriod }} # second
      availableInterval: 365 # day
      gameTypes:
        - NBA
        - MLB
        - NPB

    mongoDb:
      db: kais
      host: "{{ .Values.config.mongoDb.host }}"
      port: {{ .Values.config.mongoDb.port }}
      username: "{{ .Values.config.mongoDb.username }}"
      password: "{{ .Values.config.mongoDb.password }}"
