---
# APP DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  template:
    metadata:
      labels:
        run: mongo
    spec:
      containers:
      - image: mongo:latest
        imagePullPolicy: Always
        name: mongo
        # env:
        # - name: FOO
        #   value: "BAR"
        ports:
        - containerPort: 27017
          protocol: TCP
          name: mgport

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    run: mongo
spec:
  type: NodePort
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: mgport
  selector:
    run: mongo