apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    run: api-server
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api-server
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: dp
    nodePort: {{ .Values.service.port }}
  selector:
    run: api-server